### ISSUE TITLE
Text complexity score seems inverted

### ISSUE THREAD

**Issue by mutatron** [atomiks/reddit-user-analyser#6]
I like this tool, but the text complexity score must be inverted.

Check out this user: https://atomiks.github.io/reddit-user-analyser/#9875432346789

Few of his sentences are more than five words long, they rarely have punctuation, and his most used words are four-letter expletives, yet he's the only user I've ever seen scored as "very high" complexity.

On the other hand users posting lengthy comments with complex grammar and large vocabulary are scored as "low" complexity.

**Comment by mayuso** [comment]
I haven't seen the code (sorry), but I'd say text complexity is not inverted.

It shows "Low" text complexity for my username on reddit, I would assume that's correct, mainly because I am not even a native English speaker.
